<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eero</string>
		<string>ero</string>
		<string>eh</string>
	</array>
	<key>name</key>
	<string>Eero</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(break|case|continue|default|do|else|for|goto|if|return|switch|typedef|while)\b</string>
			<key>name</key>
			<string>keyword.control.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(autoreleasepool|catch|finally|in|synchronized|throw|try)\b</string>
			<key>name</key>
			<string>keyword.control.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*(class|compatibility_alias|end|implementation|import|interface|protocol|using\s*prefix)\b</string>
			<key>name</key>
			<string>keyword.other.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sizeof)\b</string>
			<key>name</key>
			<string>keyword.operator.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|and_eq|bitand|bitor|compl|not|not_eq|or|or_eq|xor|xor_eq)\b</string>
			<key>name</key>
			<string>keyword.operator.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(__attribute__|__has_attribute|_Pragma|typeof|__typeof__)\b</string>
			<key>name</key>
			<string>keyword.operator.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(defs|encode|protocol)\s*(?=\()</string>
			<key>name</key>
			<string>keyword.operator.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(char|double|enum|float|int|long|short|signed|struct|union|unsigned|void)\b\s*\**</string>
			<key>name</key>
			<string>storage.type.primitive.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(_Bool|_Complex|_Imaginary|size_t|wchar_t)\b</string>
			<key>name</key>
			<string>storage.type.primitive.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Class|BOOL|id|instancetype|Protocol|SEL)\b</string>
			<key>name</key>
			<string>storage.type.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:=</string>
			<key>name</key>
			<string>storage.type.operator.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(auto|const|extern|inline|register|restrict|static|volatile)\b</string>
			<key>name</key>
			<string>storage.modifier.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(__autoreleasing|__block|__bridge|__bridge_retained|__bridge_transfer|__strong|__unsafe_unretained|__weak)\b</string>
			<key>name</key>
			<string>storage.modifier.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(assign|atomic|copy|getter|nonatomic|readonly|readwrite|retain|setter|strong|weak)\b</string>
			<key>name</key>
			<string>storage.modifier.other.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(dynamic|optional|required|synthesize)\b</string>
			<key>name</key>
			<string>storage.modifier.other.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(package|private|protected|public)\b</string>
			<key>name</key>
			<string>storage.modifier.other.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;[a-zA-Z_]+[a-zA-Z0-9_,\s]*&gt;</string>
			<key>name</key>
			<string>storage.modifier.other.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|nil|Nil|NO|NULL|__objc_no|__objc_yes|true|YES)\b</string>
			<key>name</key>
			<string>keyword constant.language.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(self|super)\b</string>
			<key>name</key>
			<string>keyword variable.language.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+[0-9_]*[.][0-9_]+([eE][+-]?[0-9_]+)?[Lf]?\b</string>
			<key>name</key>
			<string>constant.numeric.floating-point.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+[0-9_]*u?l?\b</string>
			<key>name</key>
			<string>constant.numeric.integer.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b0[xX][0-9a-fA-F_]+u?l?\b</string>
			<key>name</key>
			<string>constant.numeric.hexadecimal.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=^|[:=,(?{])\s*\|[a-zA-Z_]+[a-zA-Z0-9_:]*\|(?=\s*($|[,:)};]))</string>
			<key>name</key>
			<string>string constant.language.other.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.other.eero</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-----.*$</string>
			<key>name</key>
			<string>comment.eero</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double constant.character.eero</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>comment.placeholder.eero</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*#(define|endif|else|elif|error|if|ifdef|ifndef|line|pragma|undef|warning)\b</string>
			<key>name</key>
			<string>keyword.other.directive.eero meta.preprocessor.c</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*#(import|include)</string>
			<key>end</key>
			<string>(?=(?://|/\*))|$</string>
			<key>name</key>
			<string>keyword.other.directive.eero meta.preprocessor.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;</string>
					<key>end</key>
					<string>&gt;</string>
					<key>name</key>
					<string>string.quoted.double constant.character.eero</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double constant.character.eero</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.eero</string>
	<key>uuid</key>
	<string>EBA8223C-B300-4D85-A112-FDFC412C2F2A</string>
</dict>
</plist>
